---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: umami-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
